### ISSUE TITLE
Failed to set an indexed property on 'CSSStyleDeclaration' - Angular 13

### ISSUE THREAD

**Issue by CCanfer** [GroupeCurious/ngx-image-drawing#32]
hello everyone, does anyone else have problems with angular 13? or is this just not supported? could someone help please.

![image](https://user-images.githubusercontent.com/37589741/182768587-405b3b66-ff67-4286-92e9-f95cb916f162.png)

**Comment by awoerp** [comment]
@CCanfer I was running into this error when trying to load an image. I was able to get around it by installing an older version of fabricjs. I specifically installed  fabric v4.6.0 (The most recent version is currently v5.2.1). Hope that helps 👍

**Comment by awoerp** [comment]
After downgrading to fabric v4.6.0 I also experienced the issue outlined in this ticket:

https://github.com/GroupeCurious/ngx-image-drawing/issues/18

As suggested in that issue, further downgrading fabric to v3.2.0 corrected the issue.

**Comment by CCanfer** [comment]
thank you very much @awoerp , this solved my problem, it would be a good idea to detail in the main document
I close thread
