### ISSUE TITLE
Clear doesn't clear the last line

### ISSUE THREAD

**Issue by LeahPike** [GroupeCurious/ngx-image-drawing#6]
If I draw 4 lines then press clear the last drawn line remains.

If I draw another line, the last of the 4 lines disappears.

**Comment by venomoustoad** [comment]
Facing the same issue. The editor is really sleek but the undo and trash buttons seem to not clear the past actions until I draw the next line.

**Comment by valentintintin** [comment]
Are you using the latest version ?
It was a known bug and we thought it was fixed :/

**Comment by venomoustoad** [comment]
1.2.4 is the latest right? So I just installed fabric.js and ngx-image-drawing using npm. I see that the demo link on the github repo seems to be working fine. Am I missing some other package? 
This is from my package-lock.json in the demo which I downloaded and installed from this github repo and installed on local. 

`"ngx-image-drawing": {
      "version": "1.2.4",
      "resolved": "https://registry.npmjs.org/ngx-image-drawing/-/ngx-image-drawing-1.2.4.tgz",
      "integrity": "sha512-Zm4ZtU8ZQ1IBwixDDBQdhCDjfpoSMM7GrSHBdgBO/uscFbuoztpXflRJKVPt8SyHbdAhxUc61SqlHNTBup0WNQ==",
      "requires": {
        "tslib": "^1.9.0"
      }
    },`

`"fabric": {
      "version": "4.0.0-beta.5",
      "resolved": "https://registry.npmjs.org/fabric/-/fabric-4.0.0-beta.5.tgz",
      "integrity": "sha512-JD0TDYt50aTRBEn+3gjTUQyvRl4T9sVdhVeiXVvSnMGqHOpAkmOY7t/U0TVRUojsCvC+rmsHi633Y1feq5ovFA==",
      "requires": {
        "canvas": "^2.6.1",
        "jsdom": "^15.1.0"
      }
    },`

**Comment by valentintintin** [comment]
In the demo we use fabric@3.2.0. We didn't try with the latest v4.

`
"fabric": {
      "version": "3.2.0",
      "resolved": "https://registry.npmjs.org/fabric/-/fabric-3.2.0.tgz",
      "integrity": "sha512-vq/C1Hs90XbiHWS84eVmPryKRDN4eNMIYk+m+la+k/LXVJS9HAm/XVPTO3+wGKVNdCvzimiH5Qzs71Y1gBWJgA==",
      "dev": true,
      "requires": {
        "canvas": "^2.6.0",
        "jsdom": "15.1.0"
      }
    },
`

**Comment by LeahPike** [comment]
I'm using ngx-image-drawing@1.2.4 and fabric@4.0.0-beta.5

**Comment by venomoustoad** [comment]
Yes - it works with fabric@3.2.0.

**Comment by valentintintin** [comment]
When we'll have more time, we'll check fabric v4 ;)

**Comment by Sathishchary** [comment]
@valentintintin  I dont think it got fixed. i am using "fabric": "^4.3.0",  "ngx-image-drawing": "^1.2.4", is there anything am i missing ?
